### ISSUE TITLE
problem with // anti-pattern, maybe

### ISSUE THREAD

**Issue by tiansijie** [wangzuo/react-input-color#1]
```javascript
// anti-pattern, maybe
    if (!this._updated) {
      this.setState({
        color: getColor(cssColor)
      });
    } else {
      this._updated = false;
    }
```
```Uncaught TypeError: Cannot read property 'r' of undefined   input-color.js:17 ```

This part of code causing problem on my application when I tried to click outside of the component. Not sure why we need this part of code. I tried to comment out this part, everything is just works fine.

**Comment by tiansijie** [comment]
looks like we just need
```javascript
this.setState({
        color: getColor(cssColor)
      });
```

**Comment by wangzuo** [comment]
The problem is that there would be errors when switching a color between rgb and hsv. There are 256*256*256 colors in rgb space but only 360*100*100 colors in hsv space.

**Comment by tiansijie** [comment]
Got you. Probably I passed some invalid color value to your component which causing the error.
