### ISSUE TITLE
Use inline styles or CSS modules

### ISSUE THREAD

**Issue by idolize** [wangzuo/react-input-color#11]
Hey - love the library!

I did run into an issue, however, with CSS naming conflicts (specifically the "label" class you use conflicts with the global Bootstrap one and messes up the text style).

I suggest using either inline styles, or [CSS modules](http://glenmaddern.com/articles/css-modules) as a better way to style.

If you want to make the styles easily customizable, you can even use the awesome [react-themeable](https://github.com/markdalgleish/react-themeable) project in conjunction with CSS modules!

**Comment by wangzuo** [comment]
Thanks, css modules looks pretty cool.
