### ISSUE TITLE
color-functions dependency out of sync 

### ISSUE THREAD

**Issue by forksdeploy** [wangzuo/react-input-color#34]
in the package.json the plugin color-functions is required like this "color-functions": "^1.1.0" however because of the ^ it tries to install version 1.2.0 of color functions. color-functions library has rearranged the structure of their files this causes an error when evaluating the dependencies of react-input-color. I would suggest you lock the dependencies to a fixed version as to avoid problems like this.

**Comment by reharik** [comment]
added pr 
https://github.com/wangzuo/react-input-color/pull/35

**Comment by wangzuo** [comment]
fix in `v1.7.4`
