### ISSUE TITLE
Typescript Could not find a declaration file for module 'react-input-color'

### ISSUE THREAD

**Issue by iki789** [wangzuo/react-input-color#38]
I'm getting an error importing ColorPicker. I have a TypeScript React project and my code is just a import statement

`import { ColorPicker } from 'react-input-color';
`

And this is the error I get: 

> Could not find a declaration file for module 'react-input-color'. 'h:/Work/2019/Article Creator/article-builder/node_modules/react-input-color/dist/index.cjs.js' implicitly has an 'any' type.
>   Try `npm install @types/react-input-color` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-input-color';`

**Comment by wangzuo** [comment]
There is no type definition file yet and the color picker component is only available in the latest beta version.

**Comment by wangzuo** [comment]
Added a type definition file for typescript. Please reopen for any error since I dont use typescript.
