### ISSUE TITLE
Pulling color slider to extreme right results in NaN

### ISSUE THREAD

**Issue by priyatham-aps** [wangzuo/react-input-color#4]
As the title says, pulling the color slider to extreme right results in a NaN value. Happens in the demo page as well.

**Comment by wangzuo** [comment]
Thanks, the fix is already released in the newest version.

**Comment by priyatham-aps** [comment]
Thanks. Is it available on npm yet?

**Comment by priyatham-aps** [comment]
Just noticed that on npm that it is published. Nevermind. Thanks again for the quick fix!
